2023-04-04 01:20:08,950 INFO    MainThread:2589658 [wandb_setup.py:_flush():70] setting env: {}
2023-04-04 01:20:08,950 INFO    MainThread:2589658 [wandb_setup.py:_flush():70] multiprocessing start_methods=fork,spawn,forkserver
2023-04-04 01:20:08,950 INFO    MainThread:2589658 [wandb_setup.py:_flush():70] setting login settings: {}
2023-04-04 01:20:08,950 INFO    MainThread:2589658 [wandb_setup.py:_flush():70] setting login settings: {}
2023-04-04 01:20:08,950 INFO    MainThread:2589658 [wandb_init.py:_log_setup():318] Logging user logs to /sata_disk/jupyter-chuanhao/chuanhao_anomaly/vaelstm/scripts/wandb/run-20230404_012008-wsw2a557/logs/debug.log
2023-04-04 01:20:08,950 INFO    MainThread:2589658 [wandb_init.py:_log_setup():319] Logging internal logs to /sata_disk/jupyter-chuanhao/chuanhao_anomaly/vaelstm/scripts/wandb/run-20230404_012008-wsw2a557/logs/debug-internal.log
2023-04-04 01:20:10,254 INFO    MainThread:2589658 [wandb_run.py:_console_start():1396] atexit reg
2023-04-04 01:20:10,255 INFO    MainThread:2589658 [wandb_run.py:_redirect():1259] redirect: SettingsConsole.REDIRECT
2023-04-04 01:20:10,255 INFO    MainThread:2589658 [wandb_run.py:_redirect():1264] Redirecting console.
2023-04-04 01:20:10,255 INFO    MainThread:2589658 [redirect.py:install():213] install start
2023-04-04 01:20:10,256 INFO    MainThread:2589658 [redirect.py:install():228] install stop
2023-04-04 01:20:10,256 INFO    MainThread:2589658 [redirect.py:install():213] install start
2023-04-04 01:20:10,256 INFO    MainThread:2589658 [redirect.py:install():228] install stop
2023-04-04 01:20:10,256 INFO    MainThread:2589658 [wandb_run.py:_redirect():1310] Redirects installed.
2023-04-04 01:20:10,257 INFO    MainThread:2589658 [wandb_run.py:_atexit_cleanup():1366] got exitcode: 1
2023-04-04 01:20:10,257 INFO    MainThread:2589658 [wandb_run.py:_restore():1338] restore
2023-04-04 01:20:10,258 INFO    MainThread:2589658 [redirect.py:uninstall():232] uninstall start
2023-04-04 01:20:10,258 INFO    MainThread:2589658 [redirect.py:_stop():287] _stop: stdout
2023-04-04 01:20:10,258 INFO    stdout    :2589658 [redirect.py:_pipe_relay():129] relay done saw last write: stdout
2023-04-04 01:20:10,259 INFO    MainThread:2589658 [redirect.py:_stop():293] _stop closed: stdout
2023-04-04 01:20:10,259 INFO    stdout    :2589658 [redirect.py:_pipe_relay():145] relay done done: stdout
2023-04-04 01:20:10,259 INFO    MainThread:2589658 [redirect.py:_stop():299] _stop joined: stdout
2023-04-04 01:20:10,259 INFO    MainThread:2589658 [redirect.py:_stop():301] _stop rd closed: stdout
2023-04-04 01:20:10,259 INFO    MainThread:2589658 [redirect.py:uninstall():236] uninstall done
2023-04-04 01:20:10,259 INFO    MainThread:2589658 [redirect.py:uninstall():232] uninstall start
2023-04-04 01:20:10,259 INFO    MainThread:2589658 [redirect.py:_stop():287] _stop: stderr
2023-04-04 01:20:10,259 INFO    stderr    :2589658 [redirect.py:_pipe_relay():129] relay done saw last write: stderr
2023-04-04 01:20:10,259 INFO    MainThread:2589658 [redirect.py:_stop():293] _stop closed: stderr
2023-04-04 01:20:10,259 INFO    stderr    :2589658 [redirect.py:_pipe_relay():145] relay done done: stderr
2023-04-04 01:20:10,260 INFO    MainThread:2589658 [redirect.py:_stop():299] _stop joined: stderr
2023-04-04 01:20:10,260 INFO    MainThread:2589658 [redirect.py:_stop():301] _stop rd closed: stderr
2023-04-04 01:20:10,260 INFO    MainThread:2589658 [redirect.py:uninstall():236] uninstall done
2023-04-04 01:20:10,599 INFO    MainThread:2589658 [wandb_run.py:_wait_for_finish():1489] got exit ret: file_counts {
  wandb_count: 2
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 37615
  total_bytes: 37615
}

2023-04-04 01:20:12,604 INFO    MainThread:2589658 [wandb_run.py:_wait_for_finish():1489] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 6
  other_count: 1
}
pusher_stats {
  uploaded_bytes: 42285
  total_bytes: 42285
}

2023-04-04 01:20:13,710 INFO    MainThread:2589658 [wandb_run.py:_show_files():1711] logging synced files
2023-04-04 01:20:13,714 INFO    MainThread:2589658 [internal.py:handle_exit():139] Internal process exited
